# Generated by Django 3.1.1 on 2020-10-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AddField(
            model_name='target',
            name='inc_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('PERSON', 'Person'), ('LIFEFORM', 'Lifeform'), ('OBJECT', 'Object'), ('LOCATION', 'Location'), ('EVENT', 'Event'), ('OTHER', 'Other')], max_length=12),
        ),
    ]
