# Generated by Django 3.1.1 on 2020-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_personaltarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltarget',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
