# Generated by Django 3.1.1 on 2021-01-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20201231_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooltarget',
            name='feedback_img_chash',
        ),
    ]
